### ISSUE TITLE
Add poster of resource #1 as an image/pdf download in the site

### ISSUE THREAD

**Issue by smithkelseyj** [simplysecure/devs-guide-to#17]

**Comment by Erioldoesdesign** [comment]
should probably be uploaded here: https://github.com/simplysecure/usable-user-testing-can-be-fun-poster

and then the image links can be added into the microsite

**Comment by smithkelseyj** [comment]
I don't have access to upload

<img width="422" alt="Screen Shot 2022-03-04 at 15 33 00" src="https://user-images.githubusercontent.com/56199177/156782026-21d08dd8-c8f5-446f-bb90-e0a64371b73d.png">

**Comment by Erioldoesdesign** [comment]
@smithkelseyj just gave you admin access 😄

**Comment by smithkelseyj** [comment]
Uploaded! let me know if it's ok
