### ISSUE TITLE
email to request developers/tool teams review of the microsite content etc

### ISSUE THREAD

**Issue by Erioldoesdesign** [simplysecure/devs-guide-to#29]
- Ask for tool teams and devs to review of the microsite site. https://simplysecure.github.io/devs-guide-to/ 

- In email, invite the tool teams/devs to answer the following questions to frame the feedback:
        - What did you like?
        - What did you not like?
        - What was hard to understand?
        - Where did you need more examples?
        - What was missing?

- In the email include a link to issue in this Github where teams can write their comment response to the questions.

**Comment by Erioldoesdesign** [comment]
Hello [PERSONS NAME and/or Org],

We're reaching out to you as you previously were part of the [Usable.tools](https://usable.tools/) and/or [AXIS](https://usable.tools/blog/2020-11-18-axis/). If you weren't part of Usable.tools or AXIS then we're reaching out to you as we believe your insight and feedback on these resources are of great value.

[Simply Secure](https://simplysecure.org/) in partnership with [Internews](https://internews.org/) and [Okthanks](https://okthanks.com/) have created a microsite with a series of resources focused on helping developers and OSS tool teams better understand user centred design practices, starting with user testing as an entryway into including user voices in yoru tool development.

We'd really appreciate if you'd take a look at the microsite here: https://simplysecure.github.io/devs-guide-to/ and give us some feedback you can focus your feedback around these questions if it helps!

- What did you like?
- What did you not like?
- What was hard to understand?
- Where did you need more examples?
- What was missing?

When your ready to offer up your feedback, we'd love to make that as open source as possible so we've created [this issue](https://github.com/simplysecure/devs-guide-to/issues/58) on our repository so that you can write your feedback in a comment on the issue 😄 

Thanks,

- The folks at Simply Secure as part of the Usable.tools project

**Comment by Erioldoesdesign** [comment]
@smithkelseyj added some text above for the email, any amendments/additions?

**Comment by smithkelseyj** [comment]
Looks good! I have some amendments:

- I think the second sentence isn't needed: "If you weren't part of Usable.tools or AXIS then we're reaching out to you as we believe your insight and feedback on these resources are of great value". We should tailor the email based on what group the recipient falls into. This is a small change that can make an impact about how the email is perceived and therefore could increase the responses that we get. I edited below
- I like to write emails by leading with the "ask" upfront, and then providing the details. 
- I edited the questions so that hopefully the responses are useful. Particularly, I removed "like" and "dislike" questions. 
- Added our names to the signature to make the "ask" more personal (putting a face to it)

My edits:

> Hello [PERSONS NAME and/or Org],
> 
> We'd like your review of a design resource microsite focused on the OSS community. We're reaching out to you because [A. You previously were part of [Usable.tools](https://usable.tools/) b. You were previously part of [AXIS](https://usable.tools/blog/2020-11-18-axis/) and] your insight and feedback on these resources are of great value.
> 
> [Simply Secure](https://simplysecure.org/), in partnership with [Internews](https://internews.org/) and [Okthanks](https://okthanks.com/), have created a resources microsite that will continue to be maintained and improved for and by the community. So far, the resources are focused on helping developers and OSS tool teams better understand user-centred design practices, starting with user testing as an entryway into including user voices in tool development.
> 
> We'd really appreciate if you took a look at the microsite here: https://simplysecure.github.io/devs-guide-to/ and gave us some feedback. Please write your feedback in a comment on this issue in Github: https://github.com/simplysecure/devs-guide-to/issues/58. We chose this method to make the microsite as open source as possible
>
> You can focus your feedback around the following questions or leave any comments that are relevant.
> -     What topics or sections were most useful? Why?
> -     How could the resource microsite be improved (content or design)? 
> -     What was confusing or hard to understand? 
> -     What guides or resources would you like to see added?
> 
> Thank you very much!  😄
> 
> Best,
> Eriol & Kelsey 
> of Simply Secure (as part of the Usable.tools project)

**Comment by smithkelseyj** [comment]
Formatting is weird above. sorry about that

**Comment by smithkelseyj** [comment]
Just thinking... is there a need to put a deadline on this? No, right?

**Comment by smithkelseyj** [comment]
I started a place for us to collect emails and stay organized: https://www.notion.so/simplysecure/A-dev-s-guide-website-repo-db74dfccd5e940e990c3cfa0f8e50075#b06d8e7daabe4437b6bab112c2ea8706

**Comment by Erioldoesdesign** [comment]
> Just thinking... is there a need to put a deadline on this? No, right?

No I don't think we need to put a hard deadline on it right away then we could maybe do push reminders?
