### ISSUE TITLE
Add a contribution wishlist to the github for things that aren’t possible for us right now

### ISSUE THREAD

**Issue by smithkelseyj** [simplysecure/devs-guide-to#4]
- Various types of callouts: quotes, scripts, tips, comments

**Comment by Erioldoesdesign** [comment]
I would suggest using issues for each 'ask' and then mapping them on the project board section of github: https://github.com/eriolhugotest/devs-guide-to/projects?type=beta

We can also give them 'labels' of high, medium, low priority if we want
