### ISSUE TITLE
Check over all markdown files for URLs/Links and update them to the non-test site version of the URL

### ISSUE THREAD

**Issue by Erioldoesdesign** [simplysecure/devs-guide-to#45]
Links like this: [Move on to Planning and operations](https://eriolhugotest.github.io/devs-guide-to/planning-and-operations/)

Should look like this: [Move on to Planning and operations]({{< ref "planning-and-operations" >}} )

https://gohugo.io/content-management/cross-references/

**Comment by smithkelseyj** [comment]
I did a check and the links look great
