### ISSUE TITLE
There's something wrong with 2 README links and I'm not sure how to fix it

### ISSUE THREAD

**Issue by smithkelseyj** [simplysecure/devs-guide-to#55]
<img width="711" alt="Screen Shot 2022-03-14 at 09 37 52" src="https://user-images.githubusercontent.com/56199177/158135134-a03a249a-d02c-47ab-8074-eab7fd06b100.png">

Would changing the links to URLs work better?

**Comment by Erioldoesdesign** [comment]
ahhh yeah ok the readme file is simple markdown and I wrote a hugo related piece of code there 🤦  they can totally be replaced with regular URLs in the `[TEXT](link here)` format
