### ISSUE TITLE
Change the wording 'engagement' across micro site to 'community events' or similar wording.

### ISSUE THREAD

**Issue by Erioldoesdesign** [simplysecure/devs-guide-to#77]
Change the wording 'engagement' across micro site to 'community events' or similar wording.

Engagement was more of an internal term for our reporting.

**Comment by Erioldoesdesign** [comment]
Needs a new person to do QA across the live site

**Comment by oilsinwater** [comment]
@Erioldoesdesign please see #81 for possible fix.
