### ISSUE TITLE
Improve 'pull quote' styling - add a coloured bg to the text for contrast

### ISSUE THREAD

**Issue by Erioldoesdesign** [simplysecure/devs-guide-to#78]
The current pull quote style in the Hugo template isn't very visually striking or different to the body text:
<img width="850" alt="Screenshot 2022-08-15 at 11 19 35" src="https://user-images.githubusercontent.com/11681324/184619047-6ae37a93-069a-4c12-a278-50cacd436783.png">

I think the twitter shortcode style works better for pullquotes:

<img width="816" alt="Screenshot 2022-08-15 at 11 20 50" src="https://user-images.githubusercontent.com/11681324/184619072-bb83f580-00a4-4f4b-8012-bb4e3c86735d.png">

Test out the twitter shortcode style for the style of the 'pull quote'. See if a border and a bg colour make them more 'standout'

**Comment by Erioldoesdesign** [comment]
@oilsinwater hey Phillip, I dunno if this is as simple as copy pasting the style from the twitter shortcode into the pull quote style block but I also don't wanna lose the original pull quote code. i kind of want a 'pullquote 2' style that uses the twitter shortcode style. Any clue how this is done without breaking hugo? lol

**Comment by oilsinwater** [comment]
@Erioldoesdesign The blockquote is styled via the theme (/theme/terminal/assets/css/main.css), and doesn't appear to me to be shortcode. So indeed, I think we can make a twitter shortcode (or other variants if you wish) that won't interfere with the theme's styling of that blockquote element.

I'll get started on testing that asap. And sorry for that lag-time!!

**Comment by oilsinwater** [comment]
![image](https://user-images.githubusercontent.com/23019793/192629836-2a8c0fa8-a810-4d9c-95a1-7daa81298cd7.png)

@Erioldoesdesign please see #82 . Again, apologies for the lag time! I'm testing out the shortcode in content/planning-and-operations.md that you're referencing here. 

Within the shortcode I've added some padding and margins, attempting to stay within the current theme with the background color...left margin seems tight though but lmk. Also if you actually wanted the orange color let me know.
